name: VillagerRepellent
main: com.example.villagerrepellent.VillagerRepellentPlugin
version: 1.1.0
api-version: '1.21'
author: You
description: Repel villagers from using specific beds/job sites by position.

commands:
  vr:
    description: Repel villagers from using the block you're looking at.
    usage: /villagerrepel
    permission: villagerrepellent.repel
    aliases: [vr]

  va:
    description: Allow villagers to use the block you're looking at again.
    usage: /villagerallow
    permission: villagerrepellent.allow
    aliases: [va]


permissions:
  villagerrepellent.repel:
    description: Allows repelling villagers from POI blocks.
    default: op
  villagerrepellent.allow:
    description: Allows allowing villagers to use POI blocks again.
    default: op
